btc = Coin(symbol='BTC', fullname='Bitcoin')
eth = Coin(symbol='ETH', fullname='Ethereum')
xrp = Coin(symbol='XRP', fullname='Ripple')
ltc = Coin(symbol='LTC', fullname='Litecoin')
bch = Coin(symbol='BCH', fullname='Bitcoin Cash')
eos = Coin(symbol='EOS', fullname='Eos')
bnb = Coin(symbol='BNB', fullname='Binance Coin')
xlm = Coin(symbol='XLM', fullname='Stellar')
ada = Coin(symbol='ADA', fullname='Cardano')
usdt = Coin(symbol='USDT', fullname='Tether')
